name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ['javascript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name : Run tests
        run: npm test  

      - name: Run Prettier
        run: npx prettier --check .
        continue-on-error: true

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
        continue-on-error: true
